---
Name: mysite
After:
  0: 'framework/*'
  1: 'cms/*'
i18n:
  default_locale: en_NZ
Database:
  name: default
SSViewer:
  theme_enabled: true
  theme: default
GDBackend:
  default_quality: 90
StringField:
  extensions:
    - StringFieldManipulationExtension
SiteConfig:
  extensions:
    - SiteConfigTrackingExtension
Link:
  extensions:
    - LinkTrackingExtension
